# Generated by Django 5.2.16 on 2026-07-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('private_invite', 'Приглашение в приватный чат'), ('private_accepted', 'Приватный чат принят'), ('private_declined', 'Приватный чат отклонён'), ('private_closed', 'Приватный чат закрыт'), ('private_cancelled', 'Приглашение отменено'), ('info', 'Информация')], max_length=32),
        ),
    ]
